<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CalculatorService"
             targetNamespace="http://www.examples.com/wsdl/CalculatorService.wsdl"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://www.examples.com/wsdl/CalculatorService.wsdl"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <message name="AddRequest">
        <part name="intA" type="xsd:int"/>
        <part name="intB" type="xsd:int"/>
    </message>

    <message name="AddResponse">
        <part name="result" type="xsd:int"/>
    </message>

    <portType name="CalculatorPortType">
        <operation name="Add">
            <input message="tns:AddRequest"/>
            <output message="tns:AddResponse"/>
        </operation>
    </portType>

    <binding name="CalculatorBinding" type="tns:CalculatorPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="Add">
            <soap:operation soapAction="Add"/>
            <input>
                <soap:body use="literal" namespace="http://www.examples.com/wsdl/CalculatorService.wsdl"/>
            </input>
            <output>
                <soap:body use="literal" namespace="http://www.examples.com/wsdl/CalculatorService.wsdl"/>
            </output>
        </operation>
    </binding>

    <service name="CalculatorService">
        <port name="CalculatorPort" binding="tns:CalculatorBinding">
            <soap:address location="http://localhost:8001/calculator"/>
        </port>
    </service>
</definitions>
